global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['variant-c:8080','variant-d:8080']
  - job_name: 'jersey-jmx'
    static_configs:
      - targets: ['variant-a:9404']
